stages:
  # the name can be any but similar name to the file for better clarity
  make_dataset:
    # the command to run the script of run a python file (.\src\data\make_dataset.py) using python and passing a parameter (.\data\raw\creditcard.csv)
    # the parameter will be taken by the make_dataset.py as sys.argv[1]
    cmd: python .\src\data\make_dataset.py .\data\raw\creditcard.csv
    # dependencies of the command (order does not matter)
    deps:
    - .\data\raw\creditcard.csv
    - .\src\data\make_dataset.py
    # parameters to be passed to the command from the params.yaml file under the make_dataset section
    # It is not compulsory to pass the params and without it, the command will also run.
    params:
    - make_dataset.test_split
    - make_dataset.seed
    # outputs of the command (order does not matter) and where it will be stored or placed
    outs:
    - .\data\processed\
  train_model:
    cmd: python .\src\models\train_model.py .\data\processed\
    deps:
    - .\data\processed\
    - .\src\models\train_model.py
    outs:
    - .\models\
  visualize:
    cmd: python .\src\visualization\visualize.py .\models\model.joblib .\data\processed\
    deps:
    - .\data\processed\
    - .\models\model.joblib
    - .\src\visualization\visualize.py
    outs:
    - dvclive

metrics:
- dvclive\metrics.json

plots:
# - dvclive\plots\images\importance.png
# - dvclive\plots\sklearn\roc\train.json:
#     template: simple
#     x: fpr
#     y: tpr
#     title: Receiver operating characteristic (ROC)
#     x_label: False Positive Rate
#     y_label: True Positive Rate
# - dvclive\plots\sklearn\prc\train.json:
#     template: simple
#     x: recall
#     y: precision
#     title: Precision-Recall Curve
#     x_label: Recall
#     y_label: Precision
# - dvclive\plots\sklearn\cm\train.json:
#     template: confusion
#     x: actual
#     y: predicted
#     title: Confusion Matrix
#     x_label: True Label
#     y_label: Predicted Label
# - dvclive\plots\sklearn\roc\test.json:
#     template: simple
#     x: fpr
#     y: tpr
#     title: Receiver operating characteristic (ROC)
#     x_label: False Positive Rate
#     y_label: True Positive Rate
# - dvclive\plots\sklearn\prc\test.json:
#     template: simple
#     x: recall
#     y: precision
#     title: Precision-Recall Curve
#     x_label: Recall
#     y_label: Precision
# - dvclive\plots\sklearn\cm\test.json:
#     template: confusion
#     x: actual
#     y: predicted
#     title: Confusion Matrix
#     x_label: True Label
#     y_label: Predicted Label
  - ROC:
      template: simple
      x: fpr
      y:
        dvclive\plots\sklearn\roc\train.json: tpr
        dvclive\plots\sklearn\roc\test.json: tpr
  - Confusion-Matrix:
      template: confusion
      x: actual
      y:
        dvclive\plots\sklearn\cm\train.json: predicted
        dvclive\plots\sklearn\cm\test.json: predicted
  - Precision-Recall:
      template: simple
      x: recall
      y:
        dvclive\plots\sklearn\prc\train.json: precision
        dvclive\plots\sklearn\prc\test.json: precision





