name: CI Pipeline

# Note: AWS_REGION will be ap-south-1 if Availability Zone under the Instances in EC2 in AWS is ap-south-1b.

# This pipeline can also include make data and train model and tune model if ci/cd is done through AWS.
# But, In this example we have performed make data and train model and tune model in the local machine.

# This workflow is triggered on every push to the main branch.
on:
  push:

# permissions required to perform the below jobs
permissions:
  id-token: write
  contents: read

jobs:
  # Continuous Integration (CI) : we can also add parameter check in the CI part
  integration:
    # this job runs on the latest version of Ubuntu
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      # this step checks out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # this step Lint the code
      - name: Lint code
        run: echo "Linting repository"

      # this step run the unit tests
      - name: Run unit tests
        run: echo "Running unit tests"

# if the code has worked fine in the independent machine as mentioned in the above step of CI, we can proceed to with the docker/image creation.

  # if CI is successful, then proceed to the next step
  # containerization of project (converting into image) and pushing the image to the ECR (Amazon Elastic Container Registry)
  build-and-push-ecr-image:
    name: Build/Push Image to ECR
    # work when integration job is successful # without needs it will run in parallel
    needs: integration
    # this job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest
    steps:
      # this step checks out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # this step install basic utilities
      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      # this step configure the AWS credentials and loading the credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # this step login to the Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # this step build the docker image, tag and push it to the Amazon EC2
      # before this you are required to create EC2 instance
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          IMAGE_TAG: latest
        run: |
          # Build a docker container and
          # push it to ECR with the latest image tag so that it can be deployed to ECS.
          # lastly print
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  # if the image build and push is successful, then proceed to the next step
  # Continuous Deployment (CD): pull the image from the ECR and run it on the EC2 instance
  Continuous-Deployment:
    name: Continuous Deployment
    # runner : a operating system which perform the job and delete the job after the job is done
    # self-hosted runner : a private runner because if your runner needs to install very big libraries (docker), softwares
    # and each time you use a normal/generic runner it will take to much time takes too much time. 
    # Also, we can add the part of code that we have to do again and again for each runner.
    # setting > actions > Runners > New self-hosted runner > select the OS > it will give you commands to run on EC2 instance terminal
    # open the AWS > EC2 instance (if not then create) > click on instance ID > connect > EC2 instance connect > connect > open EC2 instance terminal
    # If asked name of the self-hosted runner give "creditcard-runner" or any other name else press Enter to continue with default.
    # to run it "./run.sh" in terminal and Status of the runner will be Idle and press ctrl + c to stop the self-hosted runner
    # with self-hosted runner you can access the application from the public IP of the EC2 instance i.e. https://3.7.254.53:8080 then it will show the main page of the app
    # with ubuntu-latest, runner will be provided by the GitHub Actions and it will deploy the app and delete the app after the job is done. So, we need self-hosted to run the app continuously.
    runs-on: ubuntu-latest # [self-hosted, creditcard-runner] # ubuntu-latest
    # run when the build-and-push-ecr-image job is successful
    needs: build-and-push-ecr-image
    steps:
      - name: Configure AWS credentials
        # this step configure the AWS credentials and loading the credentials (for each job separately as mostly each job is written in a separate file)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # this step will login to the Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      # this step will pull the latest image from the ECR
      - name: Pull latest images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      
      # deleting the previous container
      - name: Delete Previous Container
        run: |
          docker rm -f creditcard || true

      # this step will run the docker image
      - name: Run Docker Image to serve users
        run: |
          docker run -d -p 8080:8080 --ipc="host" --name=creditcard -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' -e 'AWS_REGION=${{ secrets.AWS_REGION }}'  ${{secrets.AWS_ECR_LOGIN_URI}}/${{ secrets.ECR_REPOSITORY_NAME }}:latest